services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anythink_market
    ports:
      - 55432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-root-user.sql:/docker-entrypoint-initdb.d/init-root-user.sql

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./node-server/src:/usr/src/app/src
    depends_on:
      - postgres

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./express-server/src:/usr/src/app/src

volumes:
  pgdata:
