services:
  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./node-server/src:/usr/src/app/src

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./express-server/src:/usr/src/app/src
